### ISSUE TITLE
挺不错的一款工具，有没有想法把它做成一个可运行在服务器上的服务

### ISSUE THREAD

**Issue by BruceOuyang** [cjsliuj/SResigner#3]
如果是做成一个服务，那么就可以暴露给其他朋友使用了，不需要每台机器上都run这个应用。

**Comment by cjsliuj** [comment]
做成服务就得需要服务器，然后上传下载ipa都需要流量，这些开销都不小。
市场上已经有很多这种服务了，一个人去维护那种系统不是很现实。
